refactor(post-list): use icons for loading states
  Summary
    Remove the bootstrap progress bar and use a loading|error|warning
    icon instead.

  Notes
    loading:    spinner
    noPosts:    yellow triangular exclamation
    error:      red exclamation mark

  Implement
    + use themed colors for icons

  Test
    + test that initError displays error message
    + fix noPosts test: ensure  a "no posts" message is displayed
      when status is loaded (with no posts) - instead of on error

  Refactor
    + replace progress bar and other loading state messages with
      font-awesome icons